UART port path=/dev/ttyS1
UART baudrate=921600
UART flow control=1
SPI port path=/dev/spidev1.0
SPI frequency=24000000
SPI bit order=0
SPI CPHA=0
SPI CPOL=0
debug port path=/dev/ttyS2
debug port baudrate=921600
debug port flow control=1
Power control gpio=479
Reset GNSS gpio=
Notify GNSS gpio=478
NMEA file path=/etc/default/anld/location.dat
LOG path=/etc/default/anld/log.dat
DA path=/etc/default/anld/da/ag3352_da.bin
image path=/etc/default/anld/load/flash_download.cfg
EPO file path=/etc/default/anld/epo
EPO host=wpepodownload.mediatek.com
EPO vendor=
EPO project=
EPO device id=
